### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by Maxime-Antoine**
Hi Brad,
Thanks for this package!
While using it on a personal project I added a couple features to format data and be able to custom name tabs.
Would you be interested in adding them to the package ?
Cheers

### CODE REVIEW

**Comment by bradwestness** [comment]
I do like the idea of respecting the DisplayFormat attribute, but you can already control the worksheet name by using a DisplayName attribute on the class, so that seems redundant, and I really want to keep the function call as simple as possible.

**Comment by Maxime-Antoine** [comment]
I added the possibility to specify the worksheets names to deal with the case where several tabs use the same class (ie: orders split over worksheet/month). In this case, using DisplayName attribute as worksheet name, several worksheets are created with the same name raising an exception.

**Comment by bradwestness** [comment]
But the wsName parameter is only on the single-collection Create() call, so you couldn't use it with multiple collections anyway. I don't understand what the use-case is for having multiple worksheets with the same data in them...?

**Comment by Maxime-Antoine** [comment]
Actually the case I wanted to primarily address is something like this :

`var data = new List<IEnumerable<object>>();`
`data.Add(db.Orders.Where(Date.Month = 1);`
`data.Add(db.Orders.Where(Date.Month = 2);`
`.`
`.`
`data.Add(db.Orders.Where(Date.Month = 12);`
`Spreadsheet.Create(data);`

Which would cause an exception with `Create(IEnumerable<IEnumerable<object>> data)` as all worksheets would be tentatively created with the same name from `DisplayName` attribute on `Orders` class.

I address this by `Create(IDictionary<string, IEnumerable<object>> data)` : 

`var data = new Dictionary<IEnumerable<object>>();`
`data.Add('Jan orders', db.Orders.Where(Date.Month = 1);`
`data.Add('Feb orders', db.Orders.Where(Date.Month = 2);`
`.`
`.`
`data.Add('Dec orders', db.Orders.Where(Date.Month = 12);`
`Spreadsheet.Create(data);`

You could indeed have a different type for each worksheet but it can quickly lead to the creation of a lot of empty types (already 12 in this example, which multiplies if you includes several years etc...).

The `Create(IEnumerable<object> data, string wsName = null)` is actually not so useful as it creates only 1 worksheet.

**Comment by bradwestness** [comment]
While I appreciate the effort, I'm have plans to implement some of this in a different way, so I'm going to go ahead and close this PR. No hard feelings. :smile:

**Pull request closed without merging**
